#!/usr/bin/env python3.11
"""Emit the frozen combiner model (_model.json) + TMPL0 codebook (_tmpl0.json) as
C# 7.3 compile-time constant initializers for the v0.2 shared core.

Numbers are emitted via repr(float(...)) which is the shortest round-trip decimal;
double.Parse / System.Text.Json.GetDouble of that string yields the SAME IEEE double
the harness parsed from the original JSON token -> bit-identical embedding.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.normpath(os.path.join(HERE, "..", "harness_data"))


def num(x):
    if x is None:
        return "double.NaN"
    return repr(float(x))


def arr(vals, per=10):
    out, line = [], []
    for i, v in enumerate(vals):
        line.append(num(v))
        if len(line) == per:
            out.append("            " + ", ".join(line) + ",")
            line = []
    if line:
        out.append("            " + ", ".join(line) + ",")
    body = "\n".join(out)
    if body.endswith(","):
        body = body[:-1]
    return body


def iarr(vals, per=20):
    out, line = [], []
    for v in vals:
        line.append(str(int(v)))
        if len(line) == per:
            out.append("            " + ", ".join(line) + ",")
            line = []
    if line:
        out.append("            " + ", ".join(line) + ",")
    body = "\n".join(out)
    if body.endswith(","):
        body = body[:-1]
    return body


def sarr(vals):
    return ", ".join('"%s"' % v for v in vals)


def main():
    m = json.load(open(os.path.join(DATA, "_model.json")))
    t = json.load(open(os.path.join(DATA, "_tmpl0.json")))

    lines = []
    A = lines.append
    A("    // ===================================================================")
    A("    // FROZEN MODEL CONSTANTS -- generated by v02/gen_data.py from")
    A("    //   research/nt8_port/csharp/harness_data/_model.json")
    A("    //   research/nt8_port/csharp/harness_data/_tmpl0.json")
    A("    // DO NOT hand-edit. Numbers are shortest-round-trip decimals (bit-exact).")
    A("    // ===================================================================")
    A("    static class ModelData")
    A("    {")
    A('        public static readonly string[] Topk = { %s };' % sarr(m["topk"]))
    A('        public static readonly string[] Cols = { %s };' % sarr(m["cols"]))
    A("        public static readonly double[] Coef = {")
    A(arr(m["coef"]))
    A("        };")
    A("        public static readonly double[] Mu = {")
    A(arr(m["mu"]))
    A("        };")
    A("        public static readonly double[] Sd = {")
    A(arr(m["sd"]))
    A("        };")
    A("        public const double Threshold = %s;" % repr(float(m["threshold"])))
    A("        public const long ConsensusS = %d;" % int(m["consensus_s"]))
    A("    }")
    A("")

    tpls = t["templates"]
    nt = len(tpls)
    cents = []
    lfs = []
    mcs = []
    for tp in tpls:
        cents.extend(tp["centroid"])
        lfs.append(tp["long_frac"])
        mcs.append(tp["member_count"])
    assert len(cents) == nt * 6

    A("    static class Tmpl0Data")
    A("    {")
    A("        public const int NTemplates = %d;" % nt)
    A('        public static readonly double[] ScalerMean = { %s };' %
      ", ".join(num(v) for v in t["scaler_mean"]))
    A('        public static readonly double[] ScalerScale = { %s };' %
      ", ".join(num(v) for v in t["scaler_scale"]))
    A("        // %d templates x 6 dims, row-major (raw centroids, standardized at init)" % nt)
    A("        public static readonly double[] Centroids = {")
    A(arr(cents, per=6))
    A("        };")
    A("        public static readonly double[] LongFrac = {")
    A(arr(lfs, per=12))
    A("        };")
    A("        public static readonly int[] MemberCount = {")
    A(iarr(mcs, per=20))
    A("        };")
    A("    }")

    out = "\n".join(lines) + "\n"
    dst = os.path.join(HERE, "_generated_data.cs.inc")
    open(dst, "w", newline="\n").write(out)
    print("wrote", dst, "templates=", nt, "bytes=", len(out))


if __name__ == "__main__":
    main()
