import torch

class VTraceReconciliation:
    """
    V-trace Importance Sampling Mathematics
    Reconciles off-policy trajectories generated by highly constrained agents 
    (Worlds 2, 3, 4) before applying gradients to the Master Network.
    """
    def __init__(self, rho_bar=1.0, c_bar=1.0):
        self.rho_bar = rho_bar
        self.c_bar = c_bar

    def compute_importance_weights(self, target_pi: torch.Tensor, behavior_mu: torch.Tensor) -> torch.Tensor:
        """
        Calculates the truncated importance sampling ratio rho.
        target_pi: The Master Network's current probability of taking the action.
        behavior_mu: The constrained Agent's original probability of taking the action.
        """
        # Prevent division by zero
        behavior_mu = torch.clamp(behavior_mu, min=1e-8)
        
        # Calculate ratio: pi(a|x) / mu(a|x)
        ratio = target_pi / behavior_mu
        
        # Truncate to prevent gradient explosion
        rho = torch.clamp(ratio, max=self.rho_bar)
        return rho

    def compute_trace_correction(self, target_pi: torch.Tensor, behavior_mu: torch.Tensor) -> torch.Tensor:
        """
        Calculates the value-trace correction coefficient c.
        """
        behavior_mu = torch.clamp(behavior_mu, min=1e-8)
        ratio = target_pi / behavior_mu
        c = torch.clamp(ratio, max=self.c_bar)
        return c

    def apply_gradient_correction(self, q_loss: torch.Tensor, target_pi: torch.Tensor, behavior_mu: torch.Tensor) -> torch.Tensor:
        """
        Applies the V-trace rho coefficient directly to the temporal difference Q-loss.
        """
        rho = self.compute_importance_weights(target_pi, behavior_mu)
        
        # Detach rho so it acts as a constant multiplier, not part of the autograd graph
        rho = rho.detach()
        
        # The corrected loss to backpropagate
        corrected_loss = rho * q_loss
        return corrected_loss.mean()
