"""Extract primitive features for all cubic candidates across all DATA/cusp_picks/
canonical files to form the training set for the candidate filter classifier.

For each candidate generated by the cubic locator:
  target=1 if the user accepted/adjusted it (marked a pick <= 3 bars away)
  target=0 if the user ignored it
"""
from __future__ import annotations
import csv
import glob
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
from tools.viz.cusp_marker import compute_anchor
from archive.tools.research.data import load_atlas_tf
from tools.viz.core.feature_utils import compute_primitive_arrays
from tools.viz.core.cubic_utils import find_raw_turns

OUT_PATH = 'DATA/cusp_picks/features/candidate_primitives.csv'

def extract_candidates_for_day(date_str: str, picks: list, cubic_N: int = 20) -> tuple[list, int]:
    """
    Recompute features for all cubic candidates in the days spanning the picks.
    Labels target=1 if the candidate is near a user pick (<=3 bars), else target=0.
    Returns (candidate_rows, human_fresh_count)
    """
    if not picks:
        return [], 0
        
    df = load_atlas_tf('DATA/ATLAS', '1m')
    
    # Find the min and max timestamps of the picks
    pick_ts = [p['timestamp'] for p in picks]
    min_ts = min(pick_ts)
    max_ts = max(pick_ts)
    
    # Pad by 1 day on each side to ensure we have enough data for rolling windows and the full pick days
    t_start = min_ts - 86400
    t_end = max_ts + 86400
    
    mask = (df['timestamp'] >= t_start) & (df['timestamp'] <= t_end)
    df = df[mask].reset_index(drop=True)

    if df.empty:
        print(f'  [{day_str}] no 1m bars, skipping')
        return [], 0
    ts = df['timestamp'].values.astype(np.int64)
    close = df['close'].values.astype(float)

    # Anchors
    M_15s, S_15s = compute_anchor('15s', ts, t_start, t_end, window=20, column='close')
    M_1m,  S_1m  = compute_anchor('1m',  ts, t_start, t_end, window=15, column='close')
    M_15m, S_15m = compute_anchor('15m', ts, t_start, t_end, window=12, column='close')
    Mh,    Sh    = compute_anchor('1h',  ts, t_start, t_end, window=12, column='high')
    Ml,    Sl    = compute_anchor('1h',  ts, t_start, t_end, window=12, column='low')
    Mc,    Sc    = compute_anchor('1h',  ts, t_start, t_end, window=12, column='close')

    anchors = {
        'M_15s': M_15s, 'S_15s': S_15s,
        'M_1m': M_1m, 'S_1m': S_1m,
        'M_15m': M_15m, 'S_15m': S_15m,
        'Mh_1h': Mh, 'Sh_1h': Sh,
        'Ml_1h': Ml, 'Sl_1h': Sl,
        'Mc_1h': Mc, 'Sc_1h': Sc
    }

    features = compute_primitive_arrays(close, anchors)
    turns, _, _, _ = find_raw_turns(close, cubic_N)

    # Map picks to their bar indices
    pick_indices = []
    for p in picks:
        pts = int(p['timestamp'])
        idx = int(np.searchsorted(ts, pts))
        if idx >= len(ts) or ts[idx] != pts:
            if idx > 0 and ts[idx - 1] <= pts:
                idx = idx - 1
            else:
                continue
        pick_indices.append(idx)

    # Label candidates
    out_candidates = []
    matched_picks = set()

    for cand in turns:
        c_idx = cand['index']
        is_accepted = 0
        direction = 'UNKNOWN'
        best_dist = float('inf')
        best_p_idx = -1
        
        for pi, p_idx in enumerate(pick_indices):
            dist = abs(c_idx - p_idx)
            if dist <= 3 and dist < best_dist:
                is_accepted = 1
                best_dist = dist
                direction = picks[pi].get('direction', 'UNKNOWN')
                best_p_idx = pi
                
        if best_p_idx != -1:
            matched_picks.add(best_p_idx)
            
        row = {
            'date': date_str,
            'bar_index': c_idx,
            'timestamp': ts[c_idx],
            'type': cand['type'],
            'target': is_accepted,
            'direction': direction,
        }
        # Add all features at this index
        for k, v in features.items():
            if v is not None and not np.isnan(v[c_idx]):
                row[k] = round(float(v[c_idx]), 4)
            else:
                row[k] = None
                
        # Slope sign-flip logic
        s10 = features['slope_15s_10m'][c_idx]
        s3 = features['slope_15s_3m'][c_idx]
        if not np.isnan(s10) and not np.isnan(s3):
            row['slope_15s_flipped_dn'] = int(s10 > 0.10 and s3 < -0.05)
            row['slope_15s_flipped_up'] = int(s10 < -0.10 and s3 > 0.05)
        else:
            row['slope_15s_flipped_dn'] = 0
            row['slope_15s_flipped_up'] = 0

        # Multi-CRM slope alignment logic
        EPS = 0.05
        up_count = 0
        down_count = 0
        for s_key in ['slope_15s_10m', 'slope_1m_10m', 'slope_15m_15m']:
            val = features[s_key][c_idx]
            if not np.isnan(val):
                if val >= EPS: up_count += 1
                if val <= -EPS: down_count += 1
        row['align_up_count'] = up_count
        row['align_down_count'] = down_count
        row['align_state'] = (
            'FULL_UP'    if up_count == 3 else
            'STRONG_UP'  if up_count == 2 and down_count == 0 else
            'FULL_DOWN'  if down_count == 3 else
            'STRONG_DN'  if down_count == 2 and up_count == 0 else
            'DIVERGENT'  if up_count >= 1 and down_count >= 1 else
            'FLAT'
        )

        out_candidates.append(row)
        
    human_fresh_count = len(picks) - len(matched_picks)
    return out_candidates, human_fresh_count

def main():
    pick_files = sorted(glob.glob('DATA/cusp_picks/picks_*_multi.json'))
    if not pick_files:
        print('No pick files found in DATA/cusp_picks/picks_*_multi.json')
        return

    all_rows = []
    total_human_fresh = 0
    total_picks = 0
    
    for path in pick_files:
        with open(path) as f:
            data = json.load(f, parse_constant=lambda x: None)
        date_str = data.get('date_range', os.path.basename(path).split('_')[1])
        if '_to_' in date_str:
            date_str = date_str.split('_to_')[0]
            
        picks = data.get('picks', [])
        # Figure out the N used for this session
        cubic_n = data.get('cubic_n', 20)
        
        print(f'{path}:  {len(picks)} picks  (start date {date_str}, cubic_n={cubic_n})')
        rows, fresh_count = extract_candidates_for_day(date_str, picks, cubic_N=cubic_n)
        all_rows.extend(rows)
        total_human_fresh += fresh_count
        total_picks += len(picks)
        print(f'  -> {len(rows)} candidates extracted ({fresh_count} human_fresh picks dropped)')

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    if not all_rows:
        print('No rows extracted.')
        return
        
    cols = list(all_rows[0].keys())
    with open(OUT_PATH, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for r in all_rows:
            w.writerow(r)
    print(f'\nWrote {len(all_rows)} candidate rows to {OUT_PATH}')

    # Summary
    df = pd.DataFrame(all_rows)
    print(f'\n=== Summary ===')
    print(f'Total candidates: {len(df)}  (Accepted: {df["target"].sum()}, Ignored: {len(df) - df["target"].sum()})')
    if total_picks > 0:
        print(f'Total user picks: {total_picks}')
        print(f'Human_fresh rate (missed by cubic): {total_human_fresh} / {total_picks} = {100*total_human_fresh/total_picks:.1f}%')
    print()

if __name__ == '__main__':
    main()
