"""
Train Pivot-Direction CNN on v2 (185D) features.
=================================================

Same task as tools/train_pivot_direction_nn.py (v1 baseline at AUC 0.63):
given the features at an RM-pivot-confirmed entry, predict whether the
trade will end profitable. Used as a filter on the RM engine.

Key differences from v1 training script:
  1. Features come from `DATA/ATLAS/FEATURES_5s_v2/` (layer-family parquets)
     loaded via `core_v2.features.load_features()`, NOT from the 91D vector
     stashed in the trade pickle.
  2. Grid shape: 8 TFs x 23 per-TF features = 8x23 (was 6x15).
  3. L0_time_of_day (global) is concatenated to the flattened CNN output
     at the FC layer, NOT forced into the per-TF grid.
  4. NO feature-space z-score normalization (Principle 6). BatchNorm2d
     inside the CNN handles scale differences instead.

Date-based split (user-specified 2026-04-23):
  - Train: 2025-02-01 to 2025-08-31        (~7 months; Jan 2025 excluded as warmup)
  - Val:   2025-09-01 to 2025-09-30        (1 month; internal, for best-epoch selection)
  - Test:  2025-10-01 to 2025-12-31        (~3 months)
  - OOS:   2026-01-01 to 2026-03-20        (~2.5 months — evaluated separately via
                                            v2 RM engine run, NOT in this script)

All bounds inclusive. Trades with day < train_start or day > test_end are dropped.
Override via --train-start / --train-end / --val-start / --val-end / --test-start / --test-end.

Inputs:
  - Trade labels: training_RM_physics_v2/output/trades/rm_is_v2.pkl
    (generated by the v2 RM engine running on v2 features)
  - v2 features: DATA/ATLAS/FEATURES_5s_v2/

Outputs:
  - reports/findings/pivot_direction_nn_v2.md
  - training_RM_physics/output/pivot_direction_cnn_v2.pt

Usage:
  python training/train_pivot_cnn_v2.py
  python training/train_pivot_cnn_v2.py --epochs 50 --lr 5e-4
  python training/train_pivot_cnn_v2.py --trades-pkl path/to/other_trades.pkl
"""
from __future__ import annotations

import argparse
import os
import pickle
import sys
from datetime import datetime

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import roc_auc_score, accuracy_score

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core_v2.features import (
    load_features,
    FEATURE_NAMES,
    N_FEATURES,
    TF_ORDER,
    N_TFS,
    DEFAULT_FEATURES_ROOT,
    _l0_names, _l1_names, _l2_names, _l3_names,
)


# Defaults
# v2 engine writes to rm_is.pkl (the _v2 signifier is already in the path prefix).
DEFAULT_TRADES_PKL = 'training_RM_physics_v2/output/trades/rm_is.pkl'
DEFAULT_OUT_MD = 'reports/findings/pivot_direction_nn_v2.md'
DEFAULT_OUT_MODEL = 'training_RM_physics_v2/output/pivot_direction_cnn_v2.pt'

# Date-based day splits (inclusive bounds). 'YYYY_MM_DD' strings compare lexicographically.
DEFAULT_TRAIN_START = '2025_02_01'
DEFAULT_TRAIN_END   = '2025_08_31'
DEFAULT_VAL_START   = '2025_09_01'
DEFAULT_VAL_END     = '2025_09_30'
DEFAULT_TEST_START  = '2025_10_01'
DEFAULT_TEST_END    = '2025_12_31'
# OOS (2026-01-01 to 2026-03-20) is intentionally NOT configured here - it is
# only evaluated via the v2 RM engine run with CNN filter enabled.

# Grid dimensions — 8 TFs x 23 per-TF features
GRID_H = N_TFS                              # 8
PER_TF_COUNT = (6 + 9 + 8)                  # L1 + L2 + L3 per TF = 23
GRID_W = PER_TF_COUNT                       # 23
# + 1 L0 global scalar concatenated at FC layer

# Temporal depth — # of consecutive 5s snapshots stacked as input.
# T=12 -> 60-second lookback ending at entry (matches the 1m zigzag
# timescale used for pivot confirmation in the RM engine).
TEMPORAL_T = 12


# ─── Feature vector reshape ────────────────────────────────────────────────

def _per_tf_feature_order(tf: str) -> list[str]:
    """The 23 per-TF feature column names in canonical (L1, L2, L3) order."""
    return _l1_names(tf) + _l2_names(tf) + _l3_names(tf)


def feature_row_to_grid(row: pd.Series) -> tuple[np.ndarray, float]:
    """Reshape a 186-column (timestamp + 185 features) row to (8x23 grid, L0 scalar).

    Args:
        row: pandas Series with at least the columns in FEATURE_NAMES.
    Returns:
        (grid: np.ndarray shape (8, 23), l0: float)
    """
    grid = np.zeros((GRID_H, GRID_W), dtype=np.float32)
    for tf_idx, tf in enumerate(TF_ORDER):
        cols = _per_tf_feature_order(tf)
        for feat_idx, col in enumerate(cols):
            v = row.get(col, np.nan)
            grid[tf_idx, feat_idx] = float(v) if pd.notna(v) else np.nan
    l0 = float(row.get('L0_time_of_day', 0.0))
    return grid, l0


# ─── Feature lookup by trade timestamp ─────────────────────────────────────

def build_feature_lookup(days: list[str], root: str) -> pd.DataFrame:
    """Load v2 features for the given days and index by 5s-aligned timestamp."""
    df = load_features(days=days, root=root, require_all=False)
    if df.empty:
        return df
    df = df.set_index('timestamp', drop=False)
    return df


def features_at_trade(trade: dict, feat_by_day: dict[str, pd.DataFrame]) -> tuple[np.ndarray, float] | None:
    """[LEGACY - static snapshot] Snap trade entry to 5s bar, return (grid, L0)."""
    day = trade['day']
    if day not in feat_by_day:
        return None
    df = feat_by_day[day]
    entry_ts = int(trade['timestamp'])
    bar_ts = (entry_ts // 5) * 5
    if bar_ts not in df.index:
        return None
    row = df.loc[bar_ts]
    if isinstance(row, pd.DataFrame):
        row = row.iloc[0]
    grid, l0 = feature_row_to_grid(row)
    if np.isnan(grid).any() or not np.isfinite(l0):
        return None
    return grid, l0


def stacked_features_at_trade(trade: dict,
                               feat_by_day: dict[str, pd.DataFrame],
                               T: int = TEMPORAL_T) -> tuple[np.ndarray, float] | None:
    """Get T consecutive 5s snapshots ENDING at the trade entry bar.

    Returns:
      (stack: np.ndarray shape (T, 8, 23), l0: float at entry moment)

    None is returned when:
      - Day's features aren't loaded
      - Entry timestamp not found in day's df
      - Fewer than T-1 bars exist before entry in that day (warmup)
      - Any NaN in the T-deep stack (feature warmup)
    """
    day = trade['day']
    if day not in feat_by_day:
        return None
    df = feat_by_day[day]
    entry_ts = int(trade['timestamp'])
    bar_ts = (entry_ts // 5) * 5
    if bar_ts not in df.index:
        return None

    # Integer-location of the entry bar. Handle duplicate-index edge case.
    try:
        entry_iloc = df.index.get_loc(bar_ts)
    except KeyError:
        return None
    if isinstance(entry_iloc, slice):
        entry_iloc = entry_iloc.stop - 1
    elif isinstance(entry_iloc, np.ndarray):
        entry_iloc = int(np.where(entry_iloc)[0][-1])

    if entry_iloc < T - 1:
        # Not enough bars before entry in this day — likely too close to session open
        return None

    rows = df.iloc[entry_iloc - T + 1 : entry_iloc + 1]
    if len(rows) != T:
        return None

    grids = []
    entry_l0 = None
    for i, (_, row) in enumerate(rows.iterrows()):
        g, l0 = feature_row_to_grid(row)
        if np.isnan(g).any() or not np.isfinite(l0):
            return None
        grids.append(g)
        if i == T - 1:
            entry_l0 = l0

    stack = np.stack(grids, axis=0).astype(np.float32)  # (T, 8, 23)
    return stack, float(entry_l0)


# ─── Dataset + model ───────────────────────────────────────────────────────

class PivotDatasetV2(Dataset):
    """Holds T-deep stacks: (N, T, 8, 23) + L0 scalars + labels."""

    def __init__(self, stacks: np.ndarray, l0s: np.ndarray, labels: np.ndarray):
        # stacks shape: (N, T, 8, 23) — T is used as the Conv2d "in_channels"
        self.stacks = torch.from_numpy(stacks).float()              # (N, T, 8, 23)
        self.l0s = torch.from_numpy(l0s).float().unsqueeze(1)       # (N, 1)
        self.labels = torch.from_numpy(labels).float()              # (N,)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, i):
        return self.stacks[i], self.l0s[i], self.labels[i]


class PivotCNN_V2(nn.Module):
    """Temporal CNN on (T, 8, 23) stacks of v2 feature grids + 1 L0 scalar.

    Time dimension T is treated as the Conv2d input-channel axis — the model
    sees grid evolution across T consecutive 5s snapshots. Each conv filter
    learns a spatial pattern weighted by how features evolved temporally.

    Architecture:
      Input:  (N, T, 8, 23)       <- T-stack of feature grids
      BN2d:   (N, T, 8, 23)       <- normalize per-channel-per-batch
      Conv1:  (N, 32, 8, 23)      <- kernel 3x3, 32 filters over T-channels
      Conv2:  (N, 32, 8, 23)
      Pool:   (N, 32, 4, 11)
      Flat:   (N, 1408) + L0 (1)  -> (N, 1409)
      FC1 -> 64 -> FC2 -> 1       <- logit
    """

    def __init__(self, T: int = TEMPORAL_T):
        super().__init__()
        self.T = T
        self.bn_in = nn.BatchNorm2d(T)
        self.conv1 = nn.Conv2d(T, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.conv2 = nn.Conv2d(32, 32, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(32)
        self.pool = nn.MaxPool2d(2, 2)
        self.flat_dim = 32 * (GRID_H // 2) * (GRID_W // 2)
        self.fc1 = nn.Linear(self.flat_dim + 1, 64)
        self.fc2 = nn.Linear(64, 1)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.3)

    def forward(self, stack: torch.Tensor, l0: torch.Tensor) -> torch.Tensor:
        # stack shape: (batch, T, 8, 23) — T acts as Conv2d input channels
        x = self.bn_in(stack)
        x = self.relu(self.bn1(self.conv1(x)))
        x = self.pool(self.relu(self.bn2(self.conv2(x))))
        x = x.flatten(1)
        x = torch.cat([x, l0], dim=1)
        x = self.dropout(self.relu(self.fc1(x)))
        return self.fc2(x).squeeze(-1)


# ─── Main training loop ────────────────────────────────────────────────────

def main(trades_pkl: str, features_root: str, epochs: int, lr: float,
         out_md: str, out_model: str, batch_size: int,
         train_start: str, train_end: str,
         val_start: str, val_end: str,
         test_start: str, test_end: str):
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f'Device: {device}')

    # 1. Load trade labels
    with open(trades_pkl, 'rb') as f:
        trades = pickle.load(f)
    print(f'Loaded {len(trades)} trades from {trades_pkl}')

    # 2. Filter: valid pnl (nonzero) and within [train_start, test_end]
    valid = [t for t in trades if t.get('pnl', 0) != 0 and 'timestamp' in t and 'day' in t]
    # Any trade outside the training+test window is dropped (includes warmup
    # Jan 2025 and all 2026 OOS trades — OOS is for step 4 engine eval, not here).
    in_window = [t for t in valid if train_start <= t['day'] <= test_end]
    dropped_out_of_window = len(valid) - len(in_window)
    valid = in_window
    print(f'Valid (pnl != 0, has timestamp + day): {len(valid)}  '
          f'(dropped {dropped_out_of_window} outside [{train_start}, {test_end}])')

    # 3. Date-based day split (user-specified)
    valid.sort(key=lambda t: (t['day'], t['timestamp']))
    train_days = set(t['day'] for t in valid if train_start <= t['day'] <= train_end)
    val_days   = set(t['day'] for t in valid if val_start   <= t['day'] <= val_end)
    test_days  = set(t['day'] for t in valid if test_start  <= t['day'] <= test_end)
    # Sanity: verify no day is in multiple splits
    overlap = (train_days & val_days) | (train_days & test_days) | (val_days & test_days)
    if overlap:
        raise RuntimeError(f'Split overlap detected on days: {sorted(overlap)}. '
                           f'Check train/val/test bounds.')
    print(f'Split bounds:')
    print(f'  Train: [{train_start}, {train_end}] -> {len(train_days)} days')
    print(f'  Val:   [{val_start}, {val_end}] -> {len(val_days)} days')
    print(f'  Test:  [{test_start}, {test_end}] -> {len(test_days)} days')

    # 4. Preload v2 features per day (required_all=False so warmup days that are
    #    missing a family don't crash — we'll skip trades with NaN lookups anyway).
    print('Loading v2 features per day...')
    feat_by_day: dict[str, pd.DataFrame] = {}
    for day in sorted(train_days | val_days | test_days):
        try:
            df = load_features(days=[day], root=features_root, require_all=False)
        except FileNotFoundError:
            continue
        if df.empty:
            continue
        df = df.set_index('timestamp', drop=False)
        feat_by_day[day] = df
    total_days = len(train_days | val_days | test_days)
    print(f'Features loaded for {len(feat_by_day)}/{total_days} days')

    # 5. Build stacked grids + labels, bucket by split.
    # Each trade -> (T, 8, 23) stack of past feature grids ending at entry.
    train_set, val_set, test_set = [], [], []
    skipped_missing_day, skipped_nan_or_warmup = 0, 0
    for t in valid:
        day = t['day']
        if day not in feat_by_day:
            skipped_missing_day += 1
            continue
        lookup = stacked_features_at_trade(t, feat_by_day, T=TEMPORAL_T)
        if lookup is None:
            skipped_nan_or_warmup += 1
            continue
        stack, l0 = lookup  # (T, 8, 23), float
        label = 1.0 if t['pnl'] > 0 else 0.0
        item = (stack, l0, label)
        if day in train_days:
            train_set.append(item)
        elif day in val_days:
            val_set.append(item)
        elif day in test_days:
            test_set.append(item)

    print(f'Skipped - missing day features: {skipped_missing_day}, '
          f'NaN/session-warmup (need {TEMPORAL_T} bars before entry): {skipped_nan_or_warmup}')

    def pack(data):
        if not data:
            return (np.empty((0, TEMPORAL_T, GRID_H, GRID_W), dtype=np.float32),
                    np.empty(0, dtype=np.float32),
                    np.empty(0, dtype=np.float32))
        stacks = np.stack([d[0] for d in data])      # (N, T, 8, 23)
        l0s = np.array([d[1] for d in data], dtype=np.float32)
        labels = np.array([d[2] for d in data], dtype=np.float32)
        return stacks, l0s, labels

    g_tr, l0_tr, lb_tr = pack(train_set)
    g_va, l0_va, lb_va = pack(val_set)
    g_te, l0_te, lb_te = pack(test_set)

    print(f'Train: {len(lb_tr)}  Val: {len(lb_va)}  Test: {len(lb_te)}')
    if len(lb_tr) == 0 or len(lb_te) == 0:
        raise RuntimeError('Empty train or test set — check feature coverage and trade file.')
    print(f'Train win%: {lb_tr.mean()*100:.1f}%  Val: {lb_va.mean()*100:.1f}%  Test: {lb_te.mean()*100:.1f}%')

    # NOTE: no feature-space z-score (Principle 6). BatchNorm2d inside the model.

    train_loader = DataLoader(PivotDatasetV2(g_tr, l0_tr, lb_tr),
                              batch_size=batch_size, shuffle=True, num_workers=0)
    val_loader = DataLoader(PivotDatasetV2(g_va, l0_va, lb_va),
                            batch_size=batch_size * 2, shuffle=False, num_workers=0)
    test_loader = DataLoader(PivotDatasetV2(g_te, l0_te, lb_te),
                             batch_size=batch_size * 2, shuffle=False, num_workers=0)

    model = PivotCNN_V2().to(device)
    opt = optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.BCEWithLogitsLoss()

    best_val_auc = 0.0
    best_state = None

    for epoch in range(epochs):
        model.train()
        for xb, lb, yb in train_loader:
            xb, lb, yb = xb.to(device), lb.to(device), yb.to(device)
            opt.zero_grad()
            logits = model(xb, lb)
            loss = loss_fn(logits, yb)
            loss.backward()
            opt.step()

        # Validate
        model.eval()
        all_preds, all_labels = [], []
        with torch.no_grad():
            for xb, lb, yb in val_loader:
                xb, lb = xb.to(device), lb.to(device)
                logits = model(xb, lb).cpu().numpy()
                all_preds.append(logits)
                all_labels.append(yb.numpy())
        if all_preds:
            preds = np.concatenate(all_preds)
            labels = np.concatenate(all_labels)
            if len(set(labels)) > 1:
                val_auc = roc_auc_score(labels, preds)
                val_acc = accuracy_score(labels, (preds > 0).astype(int))
            else:
                val_auc, val_acc = float('nan'), float('nan')
        else:
            val_auc, val_acc = float('nan'), float('nan')

        print(f'epoch {epoch+1:2d}  val AUC {val_auc:.4f}  acc {val_acc:.3f}')
        if not np.isnan(val_auc) and val_auc > best_val_auc:
            best_val_auc = val_auc
            best_state = {k: v.clone() for k, v in model.state_dict().items()}

    if best_state is None:
        raise RuntimeError('No valid val AUC observed — cannot pick a best model.')

    # 6. Test with best model
    model.load_state_dict(best_state)
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for xb, lb, yb in test_loader:
            xb, lb = xb.to(device), lb.to(device)
            logits = model(xb, lb).cpu().numpy()
            all_preds.append(logits)
            all_labels.append(yb.numpy())
    test_preds = np.concatenate(all_preds)
    test_labels = np.concatenate(all_labels)
    test_probs = 1.0 / (1.0 + np.exp(-test_preds))
    test_auc = roc_auc_score(test_labels, test_preds) if len(set(test_labels)) > 1 else float('nan')
    test_acc = accuracy_score(test_labels, (test_probs > 0.5).astype(int))

    # 7. Write report + save model
    lines = [
        '# Pivot direction NN — v2 (185D)',
        '',
        f'Generated: {datetime.now().isoformat(timespec="seconds")}',
        f'Feature spec: 185D (1 L0 + 8 TFs x 23 per-TF)',
        f'Trades: {len(valid)}  Train {len(lb_tr)} Val {len(lb_va)} Test {len(lb_te)}',
        f'Skipped: missing_day_features={skipped_missing_day}, nan_or_warmup={skipped_nan_or_warmup}',
        f'Train win%: {lb_tr.mean()*100:.1f}%  Val: {lb_va.mean()*100:.1f}%  Test: {lb_te.mean()*100:.1f}%',
        f'Best val AUC: {best_val_auc:.4f}',
        f'Test AUC: {test_auc:.4f}  accuracy: {test_acc:.3f}',
        '',
        '## v1 baseline (for comparison)',
        '',
        'v1 test AUC (91D features): 0.63 per session memory',
        f'v2 test AUC (185D features): {test_auc:.4f}',
        '',
        '## Prediction-calibration on test set',
        '',
        '| prob bucket | N trades | actual win% |',
        '|---|---:|---:|',
    ]
    bins = [(0.0, 0.3), (0.3, 0.4), (0.4, 0.5), (0.5, 0.6), (0.6, 0.7), (0.7, 1.0)]
    for lo, hi in bins:
        mask = (test_probs >= lo) & (test_probs < hi)
        if mask.sum() > 0:
            lines.append(f'| {lo:.1f} – {hi:.1f} | {int(mask.sum())} | {test_labels[mask].mean()*100:.1f}% |')

    os.makedirs(os.path.dirname(out_md), exist_ok=True)
    with open(out_md, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    os.makedirs(os.path.dirname(out_model), exist_ok=True)
    torch.save({
        'state_dict': best_state,
        'arch': 'PivotCNN_V2',
        'grid_h': GRID_H,
        'grid_w': GRID_W,
        'n_features': N_FEATURES,
        'best_val_auc': best_val_auc,
        'test_auc': test_auc,
    }, out_model)

    print()
    print(f'Wrote: {out_md}')
    print(f'Wrote: {out_model}')
    print(f'TEST AUC: {test_auc:.4f}  (baseline v1: 0.63)')


def parse_args():
    ap = argparse.ArgumentParser(description='Train v2 pivot-direction CNN on 185D features')
    ap.add_argument('--trades-pkl', default=DEFAULT_TRADES_PKL)
    ap.add_argument('--features-root', default=DEFAULT_FEATURES_ROOT)
    ap.add_argument('--epochs', type=int, default=25)
    ap.add_argument('--lr', type=float, default=1e-3)
    ap.add_argument('--batch-size', type=int, default=512)
    ap.add_argument('--out-md', default=DEFAULT_OUT_MD)
    ap.add_argument('--out-model', default=DEFAULT_OUT_MODEL)
    # Date-based splits (YYYY_MM_DD strings, inclusive)
    ap.add_argument('--train-start', default=DEFAULT_TRAIN_START)
    ap.add_argument('--train-end',   default=DEFAULT_TRAIN_END)
    ap.add_argument('--val-start',   default=DEFAULT_VAL_START)
    ap.add_argument('--val-end',     default=DEFAULT_VAL_END)
    ap.add_argument('--test-start',  default=DEFAULT_TEST_START)
    ap.add_argument('--test-end',    default=DEFAULT_TEST_END)
    return ap.parse_args()


if __name__ == '__main__':
    args = parse_args()
    main(
        trades_pkl=args.trades_pkl,
        features_root=args.features_root,
        epochs=args.epochs,
        lr=args.lr,
        out_md=args.out_md,
        out_model=args.out_model,
        batch_size=args.batch_size,
        train_start=args.train_start,
        train_end=args.train_end,
        val_start=args.val_start,
        val_end=args.val_end,
        test_start=args.test_start,
        test_end=args.test_end,
    )
