"""
Bayesian-AI - Master Dashboard Generator
Generates a consolidated Jupyter notebook for System Verification, Debugging, and Learning Simulations.
"""
import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🧠 Bayesian-AI Master Dashboard\n",
    "\n",
    "**Objective:** Consolidated interface for System Verification, Debugging, and Learning Simulations.\n",
    "**Sections:**\n",
    "1. Preflight & Environment Checks (Deep Audit)\n",
    "2. Data Pipeline Test\n",
    "3. Core Component Tests\n",
    "4. Quick Learn (3-Day Simulation)\n",
    "5. Mini Training Run (5 Iterations)\n",
    "6. Result Analysis\n",
    "7. Utilities"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Preflight & Environment Checks ✈️\n",
    "Verify Python environment, CUDA availability, and run Deep Audit."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "import plotly.express as px\n",
    "import ipywidgets as widgets\n",
    "from pathlib import Path\n",
    "from IPython.display import display, clear_output\n",
    "from numba import cuda\n",
    "\n",
    "# Add root to path\n",
    "current_dir = Path(os.getcwd())\n",
    "project_root = current_dir\n",
    "while not (project_root / 'requirements.txt').exists():\n",
    "    parent = project_root.parent\n",
    "    if parent == project_root:\n",
    "        break\n",
    "    project_root = parent\n",
    "\n",
    "if str(project_root) not in sys.path:\n",
    "    sys.path.append(str(project_root))\n",
    "print(f\"Project Root: {project_root}\")\n",
    "\n",
    "from config.settings import OPERATIONAL_MODE, RAW_DATA_PATH\n",
    "import cuda_modules.hardened_verification as hv\n",
    "\n",
    "# 1. Check Operational Mode\n",
    "print(f\"\\nOperational Mode: {OPERATIONAL_MODE}\")\n",
    "\n",
    "# 2. Check CUDA\n",
    "try:\n",
    "    if cuda.is_available():\n",
    "        print(f\"🟢 CUDA Available: {cuda.detect()}\")\n",
    "        device = cuda.get_current_device()\n",
    "        print(f\"   Device: {device.name}\")\n",
    "    else:\n",
    "        print(\"🔴 CUDA Not Available. System running in CPU mode.\")\n",
    "except Exception as e:\n",
    "    print(f\"🔴 CUDA Check Failed: {e}\")\n",
    "\n",
    "# 3. Deep Audit\n",
    "print(\"\\n--- Deep Audit ---\")\n",
    "try:\n",
    "    if hv.run_audit():\n",
    "        print(\"🟢 Deep Audit Passed\")\n",
    "    else:\n",
    "        print(\"🔴 Deep Audit Failed (See CUDA_Debug.log)\")\n",
    "except Exception as e:\n",
    "    print(f\"🔴 Audit Execution Error: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Data Pipeline Test 📊\n",
    "Validate loading of a single data file."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from training.orchestrator import get_data_source\n",
    "from tests.utils import get_test_data_files\n",
    "\n",
    "try:\n",
    "    files = get_test_data_files()\n",
    "    if not files:\n",
    "        print(\"🔴 No data files found.\")\n",
    "    else:\n",
    "        test_file = files[0]\n",
    "        print(f\"Loading {os.path.basename(test_file)}...\")\n",
    "        df = get_data_source(test_file)\n",
    "        print(f\"🟢 Load Success! Shape: {df.shape}\")\n",
    "        \n",
    "        # Store for later use\n",
    "        sample_data = df.head(1000).copy() if len(df) > 1000 else df.copy()\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"🔴 Pipeline Test Failed: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Core Component Tests ⚙️\n",
    "Verify StateVector, BayesianBrain, LayerEngine."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from core.state_vector import StateVector\n",
    "from core.bayesian_brain import BayesianBrain\n",
    "from core.layer_engine import LayerEngine\n",
    "\n",
    "print(\"--- Component Status ---\")\n",
    "\n",
    "# 1. StateVector\n",
    "try:\n",
    "    sv = StateVector.null_state()\n",
    "    assert hash(sv) is not None\n",
    "    print(\"🟢 StateVector: Operational\")\n",
    "except Exception as e:\n",
    "    print(f\"🔴 StateVector: Failed ({e})\")\n",
    "\n",
    "# 2. BayesianBrain\n",
    "try:\n",
    "    bb = BayesianBrain()\n",
    "    print(\"🟢 BayesianBrain: Initialized\")\n",
    "except Exception as e:\n",
    "    print(f\"🔴 BayesianBrain: Failed ({e})\")\n",
    "\n",
    "# 3. LayerEngine\n",
    "try:\n",
    "    le = LayerEngine(use_gpu=cuda.is_available() if 'cuda' in locals() else False)\n",
    "    print(f\"🟢 LayerEngine: Initialized (GPU={le.use_gpu})\")\n",
    "except Exception as e:\n",
    "    print(f\"🔴 LayerEngine: Failed ({e})\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Quick Learn: 3-Day Simulation 🎲\n",
    "Randomly select 3 data files and run isolated learning simulations. Robust data loading prevents OOM."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import glob\n",
    "import random\n",
    "from training.orchestrator import TrainingOrchestrator\n",
    "\n",
    "# UI Helper: Simulation Monitor\n",
    "class SimulationMonitor:\n",
    "    def __init__(self, title=\"Simulation Progress\", max_steps=100):\n",
    "        self.lbl_title = widgets.HTML(f\"<b>{title}</b>\")\n",
    "        self.progress = widgets.IntProgress(value=0, min=0, max=max_steps, description='Progress:', bar_style='info')\n",
    "        self.lbl_status = widgets.Label(value=\"Initializing...\")\n",
    "        self.log_area = widgets.Output(layout={'border': '1px solid #ccc', 'height': '200px', 'overflow_y': 'scroll'})\n",
    "        self.container = widgets.VBox(\n",
    "            [self.lbl_title, self.progress, self.lbl_status, self.log_area],\n",
    "            layout=widgets.Layout(border='2px solid #007bff', padding='10px', margin='10px 0')\n",
    "        )\n",
    "        \n",
    "    def show(self):\n",
    "        display(self.container)\n",
    "        \n",
    "    def log(self, message):\n",
    "        with self.log_area:\n",
    "            print(message)\n",
    "            \n",
    "    def update_progress(self, value, status=None):\n",
    "        self.progress.value = value\n",
    "        if status:\n",
    "            self.lbl_status.value = status\n",
    "            \n",
    "    def complete(self, success=True):\n",
    "        self.progress.value = self.progress.max\n",
    "        self.progress.bar_style = 'success' if success else 'danger'\n",
    "        self.lbl_status.value = \"Complete\" if success else \"Failed\"\n",
    "\n",
    "def run_quick_learn(monitor, verbose=False):\n",
    "    # Find data files\n",
    "    monitor.log(\"Scanning for data files...\")\n",
    "    files = glob.glob(str(project_root / 'DATA/RAW/*.parquet')) + glob.glob(str(project_root / 'DATA/RAW/*.dbn*'))\n",
    "    \n",
    "    if not files:\n",
    "        monitor.log(\"🔴 No data files found in DATA/RAW\")\n",
    "        monitor.complete(False)\n",
    "        return\n",
    "\n",
    "    # Select 3 random files\n",
    "    selected_files = random.sample(files, min(3, len(files)))\n",
    "    monitor.log(f\"Selected {len(selected_files)} files: {[os.path.basename(f) for f in selected_files]}\")\n",
    "    \n",
    "    monitor.progress.max = len(selected_files)\n",
    "    results = []\n",
    "    \n",
    "    for i, file_path in enumerate(selected_files):\n",
    "        monitor.update_progress(i, f\"Processing {os.path.basename(file_path)}...\")\n",
    "        monitor.log(f\"--- Loading {os.path.basename(file_path)} ---\")\n",
    "        \n",
    "        try:\n",
    "            # Load Single File\n",
    "            df = get_data_source(file_path)\n",
    "            monitor.log(f\"Loaded {len(df)} ticks.\")\n",
    "            \n",
    "            # Initialize Orchestrator\n",
    "            orch = TrainingOrchestrator(\n",
    "                asset_ticker='MNQ', \n",
    "                data=df, \n",
    "                output_dir='debug_outputs/quick_learn',\n",
    "                verbose=verbose\n",
    "            )\n",
    "            \n",
    "            # Run 1 iteration\n",
    "            metrics = orch.run_training(iterations=1, params={'mode': 'quick_learn'})\n",
    "            metrics['file'] = os.path.basename(file_path)\n",
    "            results.append(metrics)\n",
    "            monitor.log(f\"Result: PnL=${metrics['pnl']:.2f}, WR={metrics['win_rate']:.1%}\")\n",
    "            \n",
    "        except Exception as e:\n",
    "            monitor.log(f\"🔴 Error processing file: {e}\")\n",
    "            \n",
    "    monitor.complete(True)\n",
    "    \n",
    "    # Summary\n",
    "    if results:\n",
    "        print(\"\\n=== Quick Learn Summary ===\")\n",
    "        res_df = pd.DataFrame(results)\n",
    "        display(res_df[['file', 'total_trades', 'win_rate', 'pnl']])\n",
    "\n",
    "chk_verbose = widgets.Checkbox(value=False, description='Verbose Mode')\n",
    "btn_quick = widgets.Button(description=\"Run 3-File Sim\", button_style='info')\n",
    "\n",
    "def on_quick_click(b):\n",
    "    mon = SimulationMonitor(\"Quick Learn Simulation\")\n",
    "    mon.show()\n",
    "    run_quick_learn(mon, verbose=chk_verbose.value)\n",
    "\n",
    "btn_quick.on_click(on_quick_click)\n",
    "display(widgets.HBox([btn_quick, chk_verbose]))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Mini Training Run (5 Iterations) 🏃‍♂️\n",
    "Interactive 5-iteration training on sample data (loaded in Sec 2)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def run_mini_training(b):\n",
    "    with out_area:\n",
    "        clear_output()\n",
    "        print(\"Initializing Mini Training (5 iterations)...\")\n",
    "        \n",
    "        if 'sample_data' not in globals():\n",
    "            print(\"🔴 Sample data not loaded. Run Section 2 first.\")\n",
    "            return\n",
    "\n",
    "        try:\n",
    "            # Determine GPU usage dynamically\n",
    "            use_gpu = False\n",
    "            try:\n",
    "                use_gpu = cuda.is_available()\n",
    "            except:\n",
    "                pass\n",
    "            \n",
    "            orch = TrainingOrchestrator(\n",
    "                asset_ticker='MNQ', \n",
    "                data=sample_data, \n",
    "                output_dir='debug_outputs/mini_run',\n",
    "                use_gpu=use_gpu,\n",
    "                verbose=chk_verbose_mini.value\n",
    "            )\n",
    "            \n",
    "            res = orch.run_training(iterations=5)\n",
    "            print(\"\\n🟢 Mini Run Complete!\")\n",
    "            print(f\"Total Trades: {res['total_trades']}\")\n",
    "            print(f\"PnL: ${res['pnl']:.2f}\")\n",
    "            print(f\"Win Rate: {res['win_rate']:.1%}\")\n",
    "            \n",
    "        except Exception as e:\n",
    "            print(f\"🔴 Training Failed: {e}\")\n",
    "\n",
    "chk_verbose_mini = widgets.Checkbox(value=False, description='Verbose Mode')\n",
    "btn_run = widgets.Button(description=\"Run 5 Iterations\", button_style='primary')\n",
    "out_area = widgets.Output()\n",
    "\n",
    "btn_run.on_click(run_mini_training)\n",
    "display(widgets.VBox([widgets.HBox([btn_run, chk_verbose_mini]), out_area]))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Result Analysis 📈\n",
    "Analyze the learned probability tables."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "\n",
    "def inspect_table(path, title):\n",
    "    if not os.path.exists(path):\n",
    "        print(f\"⚪ {title}: File not found ({path})\")\n",
    "        return\n",
    "    \n",
    "    print(f\"Loading {path}...\")\n",
    "    try:\n",
    "        with open(path, 'rb') as f:\n",
    "            data = pickle.load(f)\n",
    "        \n",
    "        # Handle both raw dict and BayesianBrain object\n",
    "        table = data['table'] if isinstance(data, dict) and 'table' in data else getattr(data, 'table', {})\n",
    "        \n",
    "        print(f\"🟢 {title}: {len(table)} states learned.\")\n",
    "        \n",
    "        # Convert to DF\n",
    "        records = []\n",
    "        for state, stats in table.items():\n",
    "            total = stats['total']\n",
    "            wins = stats['wins']\n",
    "            if total > 0:\n",
    "                records.append({\n",
    "                    'total': total,\n",
    "                    'wins': wins,\n",
    "                    'win_rate': wins/total,\n",
    "                    'L1': state.L1_bias,\n",
    "                    'L5': state.L5_trend\n",
    "                })\n",
    "        \n",
    "        if records:\n",
    "            df_stats = pd.DataFrame(records)\n",
    "            fig = px.scatter(df_stats, x='total', y='win_rate', \n",
    "                             title=f'{title}: Win Rate vs Sample Size',\n",
    "                             hover_data=['L1', 'L5'])\n",
    "            fig.show()\n",
    "            \n",
    "    except Exception as e:\n",
    "        print(f\"Error analyzing table: {e}\")\n",
    "\n",
    "btn_analyze = widgets.Button(description=\"Analyze Models\")\n",
    "btn_analyze.on_click(lambda b: (\n",
    "    inspect_table('debug_outputs/quick_learn/probability_table.pkl', \"Quick Learn Temp\"),\n",
    "    inspect_table('models/probability_table.pkl', \"Main Model\"),\n",
    "    inspect_table('debug_outputs/mini_run/probability_table.pkl', \"Mini Run\")\n",
    "))\n",
    "display(btn_analyze)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Utilities 🛠️"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import shutil\n",
    "\n",
    "def clean_pycache():\n",
    "    print(\"Cleaning __pycache__...\")\n",
    "    count = 0\n",
    "    for root, dirs, files in os.walk('.'):\n",
    "        for d in dirs:\n",
    "            if d == '__pycache__':\n",
    "                shutil.rmtree(os.path.join(root, d))\n",
    "                count += 1\n",
    "    print(f\"Removed {count} directories.\")\n",
    "\n",
    "btn_clean = widgets.Button(description=\"Clear PyCache\")\n",
    "btn_clean.on_click(lambda b: clean_pycache())\n",
    "display(btn_clean)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

# Output to notebooks/debug_dashboard.ipynb
os.makedirs('notebooks', exist_ok=True)
with open('notebooks/debug_dashboard.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print("Notebook generated successfully: notebooks/debug_dashboard.ipynb")
